# Generated by Django 5.2.4 on 2025-07-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crop_feedback_mobileotp_month_news_phoneotp_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_picture',
            field=models.URLField(blank=True, default="{% static 'images/logo/logo1.png'%}", null=True),
        ),
    ]
