# Generated by Django 5.2.4 on 2025-07-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_details_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='name',
            new_name='username',
        ),
    ]
