# Generated by Django 5.2.4 on 2025-07-25 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_name_user_details_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='city',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='location',
        ),
        migrations.AddField(
            model_name='user_details',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='role',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='area_details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='flat_details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='landmark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_picture',
            field=models.URLField(default="{% static 'images/logo/logo1.png'%}", null=True),
        ),
    ]
