# Generated by Django 5.2.4 on 2025-07-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_city_seller_district_remove_seller_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketprice',
            old_name='price_per_kg',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='marketprice',
            old_name='location',
            new_name='veg_name',
        ),
        migrations.RemoveField(
            model_name='marketprice',
            name='crop',
        ),
        migrations.AlterField(
            model_name='seller',
            name='area_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='flat_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_picture',
            field=models.URLField(default='/static/images/logo/logo1.png', null=True),
        ),
    ]
