# Generated by Django 5.2.4 on 2025-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_crop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MarketPrice',
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='crop',
            name='soil_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
