# Generated by Django 5.2.4 on 2025-07-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='image',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
